language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: 0l9zrIFzM1Ww+bZac9HFzbZEcMngeDXBCRn3sppYM2vfz+/xEZtyUlE0HjMzDA+j58GXF4eU6Srm9Q1cVGVz0wcbsIIsA8cbQZFaEESMYQw//BP3YzzNHp3BZhh0fjN+7RlDBNAuLecuSnzjI874dAq3ffD5xaYy3rFh+fm/O1lh1jl2O7ysG7YJ2XXR9dWht44oCpVBsesprXPQE1TQjF/KV70W/f7Q4cM+hcquULPw3rHa7bwACzvIO8L4tSOwvHr0x8g2uYyBLQODBT9/D8eBhVwYdva3JaGdy2bOx0ST/JT/mPzNU8mUyExELBs4QDdfopODNWGwXfvVsPUmTxChbfRuur4oxj8M4wCB+yq9nl+8Nbd93PPoV6tn8VXEgYzBi83Sf7MMItlZpe/9jOjrFUiHfbXS0yB6Ca7luP+rm+JzllXzXNQTkgaDgP3fLqzFRkWU24f92q8mTbaU1EazSf6eXxODASon/4CYnNtfSfU+hIPgwmYuBXF//adPOYvpWd/EJz4nhAAFmWmOV4HLD1MiA4XTctuZJXwKGhDKqP0/7LoT9bBe3+6IxTQ9+pSLhXiLIbRV6Qt86RF5BsDx+YmJaELNSWym+UQETeQOShdEjezsgGb8/KtbTU2/nAS7MV6ejkzFJU06nk82Hg53+H8ofGgQ+70EZ6tH+Zs=
  file:
    - "remark-rehype.js"
    - "remark-rehype.min.js"
  on:
    tags: true
